import { describe, expect, test, vi } from 'vitest';
import { PlayerAuthority } from './playerAuthority';
import { ProcessLocalPlayerAuthorityRepository } from './playerRepository';
import { loadGuestCredentialConfig } from '../auth/guestCredentials';
import { signAuthenticatedTransfer } from './authenticatedTransfer';
import { applyCreatureExperience } from '../../src/games/monster-rpg/sim';
const authorityForTest = (repository: ProcessLocalPlayerAuthorityRepository, rng = () => 0.5) => new PlayerAuthority(repository, () => new Date(0), undefined, rng);
const oneCallClock = (at: Date) => {
  let calls = 0;
  return () => {
    calls += 1;
    if (calls > 1) throw new Error('authority clock was read more than once');
    return at;
  };
};
describe('PlayerAuthority', () => {
  test.each([
    ['bootstrap', async (authority: PlayerAuthority, principal: { sub: string }) => authority.bootstrapProfile(principal, { name: 'A', avatar: 'scout' })],
    ['reset', async (authority: PlayerAuthority, principal: { sub: string }) => authority.execute(principal, { intentId: 'reset', expectedRevision: 0, intent: { type: 'resetProgress', confirmed: true } })]
  ])('uses exactly one injected clock for %s', async (_family, mutate) => {
    const principal = { sub: '123e4567-e89b-42d3-a456-426614174081' };
    const repository = new ProcessLocalPlayerAuthorityRepository();
    if (_family === 'reset') await authorityForTest(repository).bootstrapProfile(principal, { name: 'A', avatar: 'scout' });
    const at = new Date('2026-07-21T12:00:00.000Z');
    const authority = new PlayerAuthority(repository, oneCallClock(at), undefined, () => 0.25);
    const random = vi.spyOn(Math, 'random'); const now = vi.spyOn(Date, 'now');
    await mutate(authority, principal);
    expect((await repository.read(principal.sub))!.save.updatedAt).toBe(at.toISOString());
    expect(random).not.toHaveBeenCalled(); expect(now).not.toHaveBeenCalled();
    vi.restoreAllMocks();
  });
  test('forwards the injected RNG through starter conversion', async () => {
    const principal = { sub: '123e4567-e89b-42d3-a456-426614174082' };
    const repository = new ProcessLocalPlayerAuthorityRepository();
    await authorityForTest(repository).bootstrapProfile(principal, { name: 'A', avatar: 'scout' });
    await authorityForTest(repository).execute(principal, { intentId: 'elder', expectedRevision: 0, intent: { type: 'completeElderDialog' } });
    let rngCalls = 0;
    const authority = new PlayerAuthority(repository, oneCallClock(new Date('2026-07-21T12:00:00.000Z')), undefined, () => { rngCalls += 1; return 0.25; });
    expect((await authority.execute(principal, { intentId: 'starters', expectedRevision: 1, intent: { type: 'convertCreatureCard', starter: true } })).status).toBe('applied');
    expect(rngCalls).toBeGreaterThan(0);
  });
  test('reset preserves identity, audit and receipt records while advancing each revision once', async () => {
    const repository = new ProcessLocalPlayerAuthorityRepository(); const authority = authorityForTest(repository);
    const principal = { sub: '123e4567-e89b-42d3-a456-426614174090' };
    await authority.bootstrapProfile(principal, { name: 'A', avatar: 'scout' });
    const before = (await repository.read(principal.sub))!;
    before.grantReceipts['battle:sealed'] = 0; before.intentReceipts.previous = { payloadHash: 'h', revision: 0 };
    expect(await repository.compareExchange(principal.sub, 0, before)).toBe(true);
    const result = await authority.execute(principal, { intentId: 'reset', expectedRevision: 0, intent: { type: 'resetProgress', confirmed: true } });
    expect(result.status).toBe('applied');
    const after = (await repository.read(principal.sub))!;
    expect(after.playerId).toBe(before.playerId);
    expect(after.save.profile.playerId).toBe(before.save.profile.playerId);
    expect(after.revision).toBe(1); expect(after.rosterRevision).toBe(1);
    expect(after.grantReceipts).toEqual(before.grantReceipts);
    expect(after.intentReceipts).toMatchObject({ previous: before.intentReceipts.previous, reset: { revision: 1 } });
    expect(after.progressionEvents).toEqual(before.progressionEvents);
  });
  test('imports only signed, account-owned absent aggregates and permits signed growth history', async () => {
    const key = Buffer.alloc(32, 7).toString('base64url'); const config = loadGuestCredentialConfig({ GAMEIT_GUEST_AUTH_KEYS: `active:${key}`, NODE_ENV: 'test' });
    const sourceRepository = new ProcessLocalPlayerAuthorityRepository(); const source = new PlayerAuthority(sourceRepository, () => new Date(1), config, () => 0.5);
    const principal = { sub: '123e4567-e89b-42d3-a456-426614174099' };
    await source.bootstrapProfile(principal, { name: 'A', avatar: 'scout' });
    expect((await source.execute(principal, { intentId: 'elder', expectedRevision: 0, intent: { type: 'completeElderDialog' } })).status).toBe('applied');
    expect((await source.execute(principal, { intentId: 'starters', expectedRevision: 1, intent: { type: 'convertCreatureCard', starter: true } })).status).toBe('applied');
    const aggregate = (await sourceRepository.read(principal.sub))!;
    // Signed transfers still reject growth drafts that were never sealed by authority.
    const creature = Object.values(aggregate.save.creatures.creatures)[0];
    const grown = applyCreatureExperience(creature, 100, 'common', { now: () => new Date('2026-07-20T00:00:00.000Z') });
    aggregate.save.creatures.creatures[grown.id] = grown;
    aggregate.revision += 1; aggregate.rosterRevision += 1;
    expect(await sourceRepository.compareExchange(principal.sub, 2, aggregate)).toBe(false);
    const exported = await source.exportAuthenticatedSave(principal);
    const target = new PlayerAuthority(new ProcessLocalPlayerAuthorityRepository(), () => new Date(2), config, () => 0.5);
    expect(await target.importAuthenticatedSave(principal, JSON.stringify(exported))).toMatchObject({ ok: true });
    expect(await target.importAuthenticatedSave({ sub: '123e4567-e89b-42d3-a456-426614174098' }, JSON.stringify(exported))).toMatchObject({ ok: false, code: 'CROSS_PRINCIPAL' });
    expect((await target.importAuthenticatedSave(principal, `${JSON.stringify(exported)}x`)).ok).toBe(false);
    expect(await target.importAuthenticatedSave(principal, 'x'.repeat(256 * 1024 + 1))).toMatchObject({ ok: false, code: 'INVALID_TRANSFER' });
  });
  test('settles growth into matching sealed ledger history without exposing drafts', async () => {
    const key = Buffer.alloc(32, 9).toString('base64url'); const config = loadGuestCredentialConfig({ GAMEIT_GUEST_AUTH_KEYS: `active:${key}`, NODE_ENV: 'test' });
    const repository = new ProcessLocalPlayerAuthorityRepository(); const authority = new PlayerAuthority(repository, () => new Date(0), config, () => 0.5);
    const principal = { sub: '123e4567-e89b-42d3-a456-426614174095' };
    await authority.bootstrapProfile(principal, { name: 'A', avatar: 'scout' });
    expect((await authority.execute(principal, { intentId: 'elder', expectedRevision: 0, intent: { type: 'completeElderDialog' } })).status).toBe('applied');
    expect((await authority.execute(principal, { intentId: 'starters', expectedRevision: 1, intent: { type: 'convertCreatureCard', starter: true } })).status).toBe('applied');
    const creatureId = (await repository.read(principal.sub))!.save.creatures.activePartyCreatureIds[0];
    const settled = await authority.settleBattle(principal, { battleId: 'sealed-battle', encounterId: 'sealed-encounter', outcome: 'defeated', playerCreatureId: creatureId, playerCreatureHp: 10, playerCreatureFainted: false, opponentCreatureHp: 0, opponentCreatureFainted: true, rewardGranted: true, rewards: { seed: 1, magicDust: 0, clinks: 0, playerExperience: 0, battlingCreatureExperience: 100, activePartyExperience: 100, materials: [] } });
    const aggregate = (await repository.read(principal.sub))!;
    expect(JSON.stringify(settled)).not.toContain('pendingGrowthEvents');
    expect(JSON.stringify(aggregate)).not.toContain('pendingGrowthEvents');
    for (const [id, creature] of Object.entries(aggregate.save.creatures.creatures)) expect(creature.statGrowth?.events ?? []).toEqual(aggregate.progressionEvents.filter((event) => event.creatureId === id));
    const exported = await authority.exportAuthenticatedSave(principal);
    expect(exported?.payload).not.toContain('pendingGrowthEvents');
    expect(JSON.parse(exported!.payload).progressionEvents).toEqual(aggregate.progressionEvents);
  });
  test('rejects a signed authenticated import containing a pending growth draft', async () => {
    const key = Buffer.alloc(32, 10).toString('base64url'); const config = loadGuestCredentialConfig({ GAMEIT_GUEST_AUTH_KEYS: `active:${key}`, NODE_ENV: 'test' });
    const principal = { sub: '123e4567-e89b-42d3-a456-426614174094' }; const source = new PlayerAuthority(new ProcessLocalPlayerAuthorityRepository(), () => new Date(0), config, () => 0.5);
    await source.bootstrapProfile(principal, { name: 'A', avatar: 'scout' });
    await source.execute(principal, { intentId: 'elder', expectedRevision: 0, intent: { type: 'completeElderDialog' } });
    await source.execute(principal, { intentId: 'starters', expectedRevision: 1, intent: { type: 'convertCreatureCard', starter: true } });
    const snapshot = (await source.snapshot(principal))!; const creature = { ...Object.values(snapshot.save.creatures.creatures)[0], pendingGrowthEvents: [{ id: 'draft', kind: 'level-up' as const, model: 'deterministic-default' as const, level: 2, deltas: { hp: 1, attack: 1, defense: 1, speed: 1, stamina: 1 }, createdAt: new Date(0).toISOString() }] };
    snapshot.save.creatures.creatures[creature.id] = creature;
    const envelope = signAuthenticatedTransfer({ playerId: principal.sub, revision: 2, rosterRevision: 1, issuedAt: 0, payload: JSON.stringify({ type: 'authority-save-v2', save: snapshot.save, progressionEvents: [] }) }, config);
    const target = new PlayerAuthority(new ProcessLocalPlayerAuthorityRepository(), () => new Date(0), config, () => 0.5);
    expect(await target.importAuthenticatedSave(principal, JSON.stringify(envelope))).toMatchObject({ ok: false, code: 'INVALID_LEGACY_SAVE' });
  });
  test('rejects authenticated imports with foreign ownership and has one concurrent create winner', async () => {
    const key = Buffer.alloc(32, 8).toString('base64url'); const config = loadGuestCredentialConfig({ GAMEIT_GUEST_AUTH_KEYS: `active:${key}`, NODE_ENV: 'test' });
    const principal = { sub: '123e4567-e89b-42d3-a456-426614174097' }; const sourceRepository = new ProcessLocalPlayerAuthorityRepository(); const source = new PlayerAuthority(sourceRepository, () => new Date(1), config, () => 0.5);
    await source.bootstrapProfile(principal, { name: 'A', avatar: 'scout' }); const aggregate = (await sourceRepository.read(principal.sub))!;
    aggregate.save.inventory.ownerPlayerId = '123e4567-e89b-42d3-a456-426614174096'; expect(await sourceRepository.compareExchange(principal.sub, 0, aggregate)).toBe(true);
    const foreign = JSON.stringify(await source.exportAuthenticatedSave(principal));
    const target = new PlayerAuthority(new ProcessLocalPlayerAuthorityRepository(), () => new Date(2), config, () => 0.5);
    expect(await target.importAuthenticatedSave(principal, foreign)).toMatchObject({ ok: false, code: 'CROSS_PRINCIPAL' });
    aggregate.save.inventory.ownerPlayerId = principal.sub; expect(await sourceRepository.compareExchange(principal.sub, 0, aggregate)).toBe(true);
    const valid = JSON.stringify(await source.exportAuthenticatedSave(principal));
    const concurrent = new PlayerAuthority(new ProcessLocalPlayerAuthorityRepository(), () => new Date(3), config, () => 0.5);
    const results = await Promise.all([concurrent.importAuthenticatedSave(principal, valid), concurrent.importAuthenticatedSave(principal, valid)]);
    expect(results.filter((result) => result.ok)).toHaveLength(1);
  });
  test('does not partially write a multi-aggregate CAS when one revision is stale', async () => {
    const repository = new ProcessLocalPlayerAuthorityRepository(); const authority = authorityForTest(repository);
    const a = { sub: '123e4567-e89b-42d3-a456-426614174010' }; const b = { sub: '123e4567-e89b-42d3-a456-426614174011' };
    await authority.bootstrapProfile(a, { name: 'A', avatar: 'scout' }); await authority.bootstrapProfile(b, { name: 'B', avatar: 'ranger' });
    const left = (await repository.read(a.sub))!; const right = (await repository.read(b.sub))!;
    const nextLeft = { ...left, revision: 1 }; const nextRight = { ...right, revision: 1 };
    expect(await repository.compareExchangeMany([{ playerId: a.sub, expectedRevision: 0, next: nextLeft }, { playerId: b.sub, expectedRevision: 9, next: nextRight }])).toBe(false);
    expect((await repository.read(a.sub))!.revision).toBe(0); expect((await repository.read(b.sub))!.revision).toBe(0);
  });
  test('uses canonical duplicate-before-revision semantics and freezes an isolated active party', async () => {
    const authority = authorityForTest(new ProcessLocalPlayerAuthorityRepository()); const principal = { sub: '123e4567-e89b-42d3-a456-426614174000' };
    const initial = await authority.bootstrapProfile(principal, { name: 'A', avatar: 'scout' });
    const stale = await authority.execute(principal, { intentId: 'x', expectedRevision: 1, intent: { type: 'moveCreatureToStorage', creatureId: 'missing' } }); expect(stale.status).toBe('rejected');
    const result = await authority.execute(principal, { intentId: 'x', expectedRevision: 0, intent: { type: 'moveCreatureToStorage', creatureId: 'missing' } }); expect(result.status).toBe('rejected');
    expect(initial.playerId).toBe(principal.sub);
  });
  test('requires an exact ready canonical party and freezes its clone', async () => {
    const repository = new ProcessLocalPlayerAuthorityRepository(); const authority = authorityForTest(repository); const principal = { sub: '123e4567-e89b-42d3-a456-426614174002' };
    await authority.bootstrapProfile(principal, { name: 'A', avatar: 'scout' }); const aggregate = (await repository.read(principal.sub))!;
    aggregate.save.creatures.activePartyCreatureIds = ['c']; aggregate.save.creatures.creatures.c = { id: 'c', ownerPlayerId: principal.sub, speciesId: 1, level: 1, experience: 0, stats: { hp: 10, attack: 1, defense: 1, speed: 1, stamina: 1 }, attacks: [], hp: 10, maxHp: 10, fainted: false, cooldowns: {} };
    expect(await repository.compareExchange(principal.sub, 0, aggregate)).toBe(true);
    const frozen = await authority.freezeReadyActiveParty({ principal, presentedCreatureIds: ['c'], expectedRosterRevision: 0 });
    expect(frozen?.creatures[0].id).toBe('c'); expect(Object.isFrozen(frozen?.creatures)).toBe(true);
    expect(await authority.freezeReadyActiveParty({ principal, presentedCreatureIds: ['other'], expectedRosterRevision: 0 })).toBeNull();
  });
  test('repository returns clones and CAS checks all records before writes', async () => {
    const repository = new ProcessLocalPlayerAuthorityRepository(); const authority = authorityForTest(repository); const principal = { sub: '123e4567-e89b-42d3-a456-426614174001' };
    await authority.bootstrapProfile(principal, { name: 'A', avatar: 'scout' }); const first = await repository.read(principal.sub); first!.save.profile.name = 'mutated'; expect((await repository.read(principal.sub))!.save.profile.name).toBe('A');
  });
  test('settles an unguarded foreign farm theft atomically and idempotently', async () => {
    const repository = new ProcessLocalPlayerAuthorityRepository(); const authority = authorityForTest(repository, () => 0);
    const attacker = { sub: '123e4567-e89b-42d3-a456-426614174030' }; const owner = { sub: '123e4567-e89b-42d3-a456-426614174031' };
    await authority.bootstrapProfile(attacker, { name: 'Attacker', avatar: 'scout' }); await authority.bootstrapProfile(owner, { name: 'Owner', avatar: 'ranger' });
    const attackerAggregate = (await repository.read(attacker.sub))!; attackerAggregate.save.inventory.currencies.magicDust = 100;
    attackerAggregate.save.position = { mapId: 'home-village', x: 0, y: 1, facing: 'east' };
    attackerAggregate.save.farms.farms.own = { id: 'own', ownerPlayerId: attacker.sub, farmType: 'magic-dust', resourceId: 'magicDust', mapId: 'home-village', position: { mapId: 'home-village', x: 2, y: 2 }, level: 1, storedResources: {}, theftCooldowns: {}, guardCreatureId: '', productionRatePerMinute: 1, storageCap: 10, lastProductionAt: new Date().toISOString() };
    expect(await repository.compareExchange(attacker.sub, 0, attackerAggregate)).toBe(true);
    const ownerAggregate = (await repository.read(owner.sub))!;
    ownerAggregate.save.farms.farms.foreign = { id: 'foreign', ownerPlayerId: owner.sub, farmType: 'magic-dust', resourceId: 'magicDust', mapId: 'home-village', position: { mapId: 'home-village', x: 1, y: 1 }, level: 1, storedResources: { magicDust: 10 }, theftCooldowns: {}, guardCreatureId: '', productionRatePerMinute: 1, storageCap: 10, lastProductionAt: new Date().toISOString() };
    expect(await repository.compareExchange(owner.sub, 0, ownerAggregate)).toBe(true);
    vi.spyOn(Math, 'random').mockReturnValue(0);
    const command = { principal: attacker, intentId: 'theft-1', expectedRevision: 0, roomMapId: 'home-village', farmId: 'foreign' };
    const result = await authority.settleUnguardedFarmTheft(command); vi.restoreAllMocks();
    expect(result.status).toBe('applied'); expect((await repository.read(owner.sub))!.save.farms.farms.foreign.storedResources.magicDust).toBeLessThan(10);
    expect((await authority.settleUnguardedFarmTheft(command)).status).toBe('duplicate');
    expect(await authority.settleUnguardedFarmTheft({ ...command, farmId: 'own' })).toMatchObject({ status: 'rejected', code: 'INTENT_REUSED' });
  });
  test('rejects forged or own farm theft commands and reports a cross-account CAS race', async () => {
    const repository = new ProcessLocalPlayerAuthorityRepository(); const authority = authorityForTest(repository); const attacker = { sub: '123e4567-e89b-42d3-a456-426614174032' }; const owner = { sub: '123e4567-e89b-42d3-a456-426614174033' };
    await authority.bootstrapProfile(attacker, { name: 'A', avatar: 'scout' }); await authority.bootstrapProfile(owner, { name: 'O', avatar: 'ranger' });
    const attackerAggregate = (await repository.read(attacker.sub))!; attackerAggregate.save.inventory.currencies.magicDust = 100;
    attackerAggregate.save.position = { mapId: 'home-village', x: 0, y: 1, facing: 'east' };
    attackerAggregate.save.farms.farms.own = { id: 'own', ownerPlayerId: attacker.sub, farmType: 'magic-dust', resourceId: 'magicDust', mapId: 'home-village', position: { mapId: 'home-village', x: 2, y: 2 }, level: 1, storedResources: {}, theftCooldowns: {}, guardCreatureId: '', productionRatePerMinute: 1, storageCap: 10, lastProductionAt: new Date().toISOString() };
    expect(await repository.compareExchange(attacker.sub, 0, attackerAggregate)).toBe(true);
    const before = await authority.snapshot(attacker);
    expect((await authority.settleUnguardedFarmTheft({ principal: attacker, intentId: 'forged', expectedRevision: 0, roomMapId: 'home-village', farmId: 'nope' })).status).toBe('rejected');
    expect((await authority.settleUnguardedFarmTheft({ principal: attacker, intentId: 'own', expectedRevision: 0, roomMapId: 'home-village', farmId: 'own' })).status).toBe('rejected');
    const ownerAggregate = (await repository.read(owner.sub))!;
    ownerAggregate.save.farms.farms.race = { id: 'race', ownerPlayerId: owner.sub, farmType: 'magic-dust', resourceId: 'magicDust', mapId: 'home-village', position: { mapId: 'home-village', x: 1, y: 1 }, level: 1, storedResources: { magicDust: 10 }, theftCooldowns: {}, guardCreatureId: '', productionRatePerMinute: 1, storageCap: 10, lastProductionAt: new Date().toISOString() };
    expect(await repository.compareExchange(owner.sub, 0, ownerAggregate)).toBe(true);
    expect(await authority.settleUnguardedFarmTheft({ principal: attacker, intentId: 'wrong-map', expectedRevision: 0, roomMapId: 'world-map', farmId: 'race' })).toMatchObject({ status: 'rejected', code: 'REJECTED' });
    attackerAggregate.save.position = { mapId: 'home-village', x: 0, y: 0, facing: 'east' };
    expect(await repository.compareExchange(attacker.sub, 0, attackerAggregate)).toBe(true);
    expect(await authority.settleUnguardedFarmTheft({ principal: attacker, intentId: 'out-of-range', expectedRevision: 0, roomMapId: 'home-village', farmId: 'race' })).toMatchObject({ status: 'rejected', code: 'REJECTED' });
    attackerAggregate.save.position = { mapId: 'home-village', x: 0, y: 1, facing: 'east' };
    expect(await repository.compareExchange(attacker.sub, 0, attackerAggregate)).toBe(true);
    ownerAggregate.save.farms.farms.race.guardCreatureId = 'guard';
    expect(await repository.compareExchange(owner.sub, 0, ownerAggregate)).toBe(true);
    expect(await authority.settleUnguardedFarmTheft({ principal: attacker, intentId: 'guarded', expectedRevision: 0, roomMapId: 'home-village', farmId: 'race' })).toMatchObject({ status: 'rejected', code: 'REJECTED' });
    ownerAggregate.save.farms.farms.race.guardCreatureId = '';
    expect(await repository.compareExchange(owner.sub, 0, ownerAggregate)).toBe(true);
    expect(await authority.settleUnguardedFarmTheft({ principal: attacker, intentId: 'stale', expectedRevision: 1, roomMapId: 'home-village', farmId: 'race' })).toMatchObject({ status: 'rejected', code: 'STALE_REVISION' });
    expect(await authority.snapshot(attacker)).toEqual(before);
    vi.spyOn(repository, 'compareExchangeMany').mockResolvedValue(false);
    const raced = await authority.settleUnguardedFarmTheft({ principal: attacker, intentId: 'race', expectedRevision: 0, roomMapId: 'home-village', farmId: 'race' });
    expect(raced).toMatchObject({ status: 'rejected', code: 'STALE_REVISION' });
    vi.restoreAllMocks();
  });
  test('reuses one injected clock across guarded-theft CAS retries', async () => {
    const repository = new ProcessLocalPlayerAuthorityRepository();
    const attacker = { sub: '123e4567-e89b-42d3-a456-426614174040' };
    const owner = { sub: '123e4567-e89b-42d3-a456-426614174041' };
    const at = new Date('2026-07-21T12:00:00.000Z');
    const setupAuthority = authorityForTest(repository);
    await setupAuthority.bootstrapProfile(attacker, { name: 'Attacker', avatar: 'scout' });
    await setupAuthority.bootstrapProfile(owner, { name: 'Owner', avatar: 'ranger' });
    const attackerAggregate = (await repository.read(attacker.sub))!;
    const attackerCreature = { id: 'attacker-creature', ownerPlayerId: attacker.sub, speciesId: 1, level: 1, experience: 0, stats: { hp: 10, attack: 2, defense: 2, speed: 2, stamina: 2 }, attacks: [], hp: 10, maxHp: 10, fainted: false, cooldowns: {} };
    attackerAggregate.save.creatures.creatures[attackerCreature.id] = attackerCreature;
    attackerAggregate.save.creatures.activePartyCreatureIds = [attackerCreature.id];
    attackerAggregate.save.inventory.currencies.magicDust = 100;
    expect(await repository.compareExchange(attacker.sub, 0, attackerAggregate)).toBe(true);
    const ownerAggregate = (await repository.read(owner.sub))!;
    const guard = { id: 'owner-guard', ownerPlayerId: owner.sub, speciesId: 1, level: 1, experience: 0, stats: { hp: 10, attack: 2, defense: 2, speed: 2, stamina: 2 }, attacks: [], hp: 10, maxHp: 10, fainted: false, cooldowns: {} };
    ownerAggregate.save.creatures.creatures[guard.id] = guard;
    ownerAggregate.save.farms.farms.guarded = { id: 'guarded', ownerPlayerId: owner.sub, farmType: 'magic-dust', resourceId: 'magicDust', mapId: 'home-village', position: { mapId: 'home-village', x: 1, y: 1 }, level: 1, storedResources: { magicDust: 10 }, theftCooldowns: {}, guardCreatureId: guard.id, productionRatePerMinute: 1, storageCap: 10, lastProductionAt: at.toISOString() };
    expect(await repository.compareExchange(owner.sub, 0, ownerAggregate)).toBe(true);
    const compare = vi.spyOn(repository, 'compareExchangeMany').mockResolvedValueOnce(false).mockResolvedValueOnce(true);
    const authority = new PlayerAuthority(repository, oneCallClock(at), undefined, () => 0.25);
    const settled = await authority.settleGuardedTheft({ attackerId: attacker.sub, ownerId: owner.sub, farmId: 'guarded', guardCreatureId: guard.id, result: { battleId: 'guarded-race', encounterId: 'guarded-encounter', outcome: 'defeated', playerCreatureId: attackerCreature.id, playerCreatureHp: 8, playerCreatureFainted: false, opponentCreatureHp: 0, opponentCreatureFainted: true, rewardGranted: false } });
    expect(settled).toBe(true);
    expect(compare).toHaveBeenCalledTimes(2);
    vi.restoreAllMocks();
  });
});
