import { GameDefinition } from '../types/game';

export const gameRegistry: GameDefinition[] = [
  {
    id: 'snake',
    name: 'Snake',
    description: 'Arcade snake with powerups, modes, and progression.',
    status: 'playable',
    accent: '#22c55e',
    route: '/games/snake',
  },
  {
    id: 'gameit-monsters',
    name: 'GameIt Monsters',
    description: 'Retro monster collecting with village exploration and online presence.',
    status: 'playable',
    accent: '#95c46d',
    route: '/games/gameit-monsters',
  },
  {
    id: 'flappy-bird',
    name: 'Flappy Bird',
    description: 'Tap through hazard gates in a bright arcade sprint.',
    status: 'coming-soon',
    accent: '#f97316',
    route: '/games/flappy-bird',
  },
  {
    id: 'stickman-fight',
    name: 'Stickman Fight',
    description: 'Fast arena duels with simple inputs and heavy hits.',
    status: 'coming-soon',
    accent: '#a855f7',
    route: '/games/stickman-fight',
  },
  {
    id: 'void-runner',
    name: 'Void Runner',
    description: 'Dash across neon lanes while the level folds around you.',
    status: 'coming-soon',
    accent: '#06b6d4',
    route: '/games/void-runner',
  },
  {
    id: 'mana-breach',
    name: 'Mana Breach',
    description: 'Build a tiny deck and break spell shields in quick rounds.',
    status: 'coming-soon',
    accent: '#ec4899',
    route: '/games/mana-breach',
  },
  {
    id: 'circuit-breaker',
    name: 'Circuit Breaker',
    description: 'Route power, dodge locks, and solve compact logic boards.',
    status: 'coming-soon',
    accent: '#6366f1',
    route: '/games/circuit-breaker',
  },
  {
    id: 'frost-bite',
    name: 'Frost Bite',
    description: 'Survive a frozen route with supplies, timing, and nerve.',
    status: 'coming-soon',
    accent: '#38bdf8',
    route: '/games/frost-bite',
  },
];
